import './globals.css'
import type { Metadata } from 'next'
import { Inter, Zen_Kaku_Gothic_New } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

const zen_Kaku_Gothic = Zen_Kaku_Gothic_New({ subsets: ['latin'], weight: ['300', '400', '500', '700']}) 

export const metadata: Metadata = {
  title: 'Next Study',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={zen_Kaku_Gothic.className}>{children}</body>
    </html>
  )
}
